[package]
name = "buoy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# common components
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
anyhow = "1.0.72"

# core components
relm4 = "0.8.1"
relm4-components = "0.8.1"
#submarine = { git = "https://github.com/eppixx/submarine" }
submarine = { path = "../submarine", features = ["navidrome"] }
gstreamer = "0.21.0"
tokio = "1.32.0"
futures = "0.3.29"
async-channel = "2.2.0"

# converting strings on seekbar
chrono = "0.4.30"

# used for loading and saving settings
serde = { version = "1.0.188", features = ["derive"] }
postcard = { version = "1.0.7", features = ["alloc"] }
toml = "0.7.8"
xdg = "2.5.2"

# for validating urls
url = "2.4.1"

