[package]
name = "buoy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
relm4 = "0.5.0"
relm4-components = "0.5.0"
chrono = "0.4.30"
anyhow = "1.0.72"
