[package]
name = "buoy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# common components
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"]}
anyhow = "1.0.86"
thiserror = "1.0.61"

# core components
relm4 = "0.8.1"
relm4-components = "0.8.1"
granite = { version = "1.2", package = "granite-rs", features = ["v7_2"] }
submarine = { git = "https://github.com/eppixx/submarine", features = ["navidrome"] }
gstreamer = "0.22.5"
tokio = { version = "1.38.0", features = ["rt", "macros", "rt-multi-thread"]}
futures = "0.3.30"
async-channel = "2.3.1"
fuzzy-matcher = "0.3.7"
rand = "0.8.5"
itertools = "0.13.0"

#mpris
zbus = "4.3.0"
zvariant = "4.1.1"

# converting strings on seekbar
chrono = "0.4.38"

# used for loading and saving settings
serde = { version = "1.0.203", features = ["derive"] }
postcard = { version = "1.0.8", features = ["alloc"] }
toml = "0.8.14"
xdg = "2.5.2"

# for validating urls
url = "2.5.0"

# desktop notifications
notify-rust = { version = "4.11.0" }


[profile.release]
strip = "debuginfo"
lto = true

[profile.dev]
strip = "debuginfo"
