[package]
name = "buoy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# common components
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
anyhow = "1.0.81"

# core components
relm4 = "0.8.1"
relm4-components = "0.8.1"
#submarine = { git = "https://github.com/eppixx/submarine" }
submarine = { path = "../submarine", features = ["navidrome"] }
gstreamer = "0.22.3"
tokio = "1.36.0"
futures = "0.3.30"
async-channel = "2.2.0"

# converting strings on seekbar
chrono = "0.4.35"

# used for loading and saving settings
serde = { version = "1.0.197", features = ["derive"] }
postcard = { version = "1.0.8", features = ["alloc"] }
toml = "0.8.12"
xdg = "2.5.2"

# for validating urls
url = "2.5.0"

