# based on: https://gitea.com/action-examples/Rust/src/branch/main/.gitea/workflows/test.yml
on: [push, pull_request]

name: Continuous integration

jobs:
  build:
    name: build
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: sudo apt-get update && sudo apt-get install -y --no-install-recommends libgtk-4-dev libgstreamer1.0-dev libgranite-7-dev && cargo build --release
      - uses: actions/upload-artifact@v4
        with:
          name: buoy
          path: target/release/buoy
